environment: "production"
server:
  port: 8080
  host: "0.0.0.0"

database:
  host: "${DB_HOST}"
  port: 5432
  name: "discord_security_prod"
  user: "${DB_USER}"
  password: "${DB_PASSWORD}"
  sslmode: "require"
  max_connections: 50

discord:
  bot_token: "${DISCORD_BOT_TOKEN}"
  alert_channel_id: "${ALERT_CHANNEL_ID}"

logging:
  level: "warn"
  format: "json"

security:
  scan_interval: "2m"
  alert_threshold: "high"
  false_positive_review: true

metrics:
  enabled: true
  port: 9090