environment: "staging"
server:
  port: 8080
  host: "0.0.0.0"

database:
  host: "${DB_HOST}"
  port: 5432
  name: "discord_security_staging"
  user: "${DB_USER}"
  password: "${DB_PASSWORD}"
  sslmode: "require"

discord:
  bot_token: "${DISCORD_BOT_TOKEN}"
  alert_channel_id: "${ALERT_CHANNEL_ID}"

logging:
  level: "info"
  format: "json"

security:
  scan_interval: "1m"
  alert_threshold: "medium"